[tool.poetry]
name = "pdfcor"
version = "0.2.0"
description = ""
authors = ["infocornouaille <90894019+infocornouaille@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.scripts]
pdfcor = "pdfcor.cli:app"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
pymupdf = "^1.24.11"
pillow = "^10.4.0"
typer = {extras = ["all"], version = "^0.9.0"}


[tool.poetry.group.dev.dependencies]
ruff = "^0.2.0" # Black removed, Ruff added

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88
target-version = "py39"

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # Pyflakes
    "W",  # pycodestyle warnings
    "I",  # isort
]
ignore = []
# fixable = ["ALL"]

[tool.ruff.format]
# quote-style = "double"
# indent-style = "space"
# skip-magic-trailing-comma = false
